on:
  workflow_call:
    inputs:
      sha:
        type: string
      repo:
        type: string
      node_type:
        type: string
        default: "cpu4"
      build_command:
        type: string
        required: true
      # Note that this is the _name_ of a secret containing the key, not the key itself.
      extra-repo-deploy-key:
        required: false
        type: string
        default: ''

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: write
  issues: none
  packages: read
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64"]
        cuda: ["12.0"]
        pkgr: ["conda", "pip"]
    runs-on: "linux-${{ matrix.arch }}-${{ inputs.node_type }}"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.sha }}
          fetch-depth: 0
      - name: Check if repo has devcontainer
        run: |
          if test -f .devcontainer/cuda${{ matrix.cuda }}-${{ matrix.pkgr }}/devcontainer.json; then
            echo "HAS_DEVCONTAINER=true" >> "${GITHUB_ENV}";
            sudo apt update;
            sudo apt install -y --no-install-recommends openssh-client;
          else
            echo "HAS_DEVCONTAINER=false" >> "${GITHUB_ENV}";
          fi
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-duration-seconds: 43200 # 12h
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - if: ${{ env.HAS_DEVCONTAINER == 'true' && inputs.extra-repo-deploy-key != '' }}
        name: Set up ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: "${{ secrets[inputs.extra-repo-deploy-key] }}"
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        name: Copy devcontainer.json file up one level
        run: |
          echo "REPOSITORY=$(basename $(pwd))" | tee -a "${GITHUB_ENV}";
          cp .devcontainer/cuda${{ matrix.cuda }}-${{ matrix.pkgr }}/devcontainer.json .devcontainer/devcontainer.json;
          if test -n "${SSH_AGENT_PID:-}" != ''; then
            cp -ar "$HOME"/.gitconfig "$HOME"/.ssh .devcontainer;
            sed -i "s@$HOME@/home/coder@g" .devcontainer/.ssh/config;
            curl -s "https://api.github.com/meta" \
            | jq -r '.ssh_keys | map("github.com \(.)") | .[]' \
            | tee .devcontainer/.ssh/known_hosts >/dev/null;
          fi
      - if: ${{ env.HAS_DEVCONTAINER == 'true' }}
        name: Run build in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          push: never
          env: |
            REPOSITORY=${{ env.REPOSITORY }}
            SCCACHE_REGION=${{ vars.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ env.AWS_ACCESS_KEY_ID }}
            AWS_SESSION_TOKEN=${{ env.AWS_SESSION_TOKEN }}
            AWS_SECRET_ACCESS_KEY=${{ env.AWS_SECRET_ACCESS_KEY }}
          runCmd: |
            cd ~/"${REPOSITORY}";
            if test -d .devcontainer/.ssh; then
              cp -ar .devcontainer/.ssh/* ~/.ssh/;
            fi
            if test -f .devcontainer/.gitconfig; then
              cat .devcontainer/.gitconfig | tee -a ~/.gitconfig;
            fi
            rm -rf .devcontainer/.ssh .devcontainer/.gitconfig;

            chmod 0700 ~/.ssh;
            chmod 0600 ~/.ssh/*;
            sudo chown -R coder:coder ~/.ssh;

            echo "gitconfig:"
            cat ~/.gitconfig;
            echo "ssh/config:"
            cat ~/.ssh/config;
            echo "ssh/known_hosts:"
            cat ~/.ssh/known_hosts;
            ls -all ~/.ssh/;

            echo "SSH_AGENT_PID: '${SSH_AGENT_PID:-}'"
            echo "SSH_AUTH_SOCK: '${SSH_AUTH_SOCK:-}'"
            if test -z "${SSH_AUTH_SOCK:-}"; then
              eval "$(ssh-agent -s)";
              ssh-add -L;
            fi

            ${{ inputs.build_command }}
